# Generated by Django 5.0.6 on 2024-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
    ]
