# Generated by Django 5.0.6 on 2024-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_customer_code_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="code",
            field=models.CharField(default="IDWJEWIOREJO", max_length=255),
            preserve_default=False,
        ),
    ]
