version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: example

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      - run:
          name: run tests
          command: python manage.py test

workflows:
  continous_integration_workflow:
    jobs:
      - build-and-test